### ISSUE TITLE
Any changes to your library from DSS Circuits

### ISSUE THREAD

**Issue by Scott216** [rambo/I2C#1]
Did you make any changes to this library or is it still the same as the one on DSS Circuits?

**Comment by VladimirAkopyan** [comment]
What? What is that an example of?

**Comment by rambo** [comment]
a REPL (except it doesn't provide a standalone REPL prompt with character echo) testing I2C, like bus-pirate but using ATMegas proper I2C hardware which supports clock stretching etc.

**Comment by Ivel97** [comment]
Correct me if I'm wrong but you've also exposed the private low-level methods:    
```
    uint8_t start();
    uint8_t sendAddress(uint8_t);
    uint8_t sendByte(uint8_t);
    uint8_t receiveByte(uint8_t);
    uint8_t stop();
```
and made them public, haven't you?

**Comment by rambo** [comment]
I think I did, to enable to "bus pirate style" REPL functionality.
