### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by mattborja** [rambo/I2C#12]
Hi,

Just wondering if we could get a LICENSE defined for this library. Looking to use this in a project to replace the built-in *Wire.h*, but noticed license appears to be undefined at this time.

My vote would be for MIT if that would be reasonable.

Thanks for your consideration.

Matt

**Comment by rambo** [comment]
Original author did no include a license but they did share the code and AFAIUnderstand knew of this repo (I sent them a comment that I made this mirror/fork/something).

The original website is gone too (https://web.archive.org/web/20190916084353/http://dsscircuits.com/index.php/articles/66-arduino-i2c-master-library for the last archive.org snapshot).

So while technically I'm not the copyright owner and thus technically can't define the licensing rules I guess we can consider that the original author did want this freely shared (and possibly improved).

**Comment by rambo** [comment]
Ah stupid me, I went and looked into the actual code, it's LGPL

**Comment by mattborja** [comment]
Yeah, actually just found it in the source files also (didn't think to look there):

- https://github.com/rambo/I2C/blob/master/I2C.h#L42
- https://github.com/rambo/I2C/blob/master/I2C.cpp#L42
Thanks!
