### ISSUE TITLE
Move method documentation to source code

### ISSUE THREAD

**Issue by bgigous** [rambo/I2C#15]
Currently, the documentation for the I2C class methods is found within the README (from #8). However, should changes be made to the code and a subsequent change(s) be needed in the documentation, it will be more difficult to update the documentation through the README file. This is because the README does not use Markdown for the methods but HTML, and additionally it is more cumbersome to make these changes in two different places (README vs method definition). Finally, many Arduino libraries keep the README concise with a summary, examples, how to contribute, etc, and put more detailed info in the source code files.

Therefore, I propose moving the documentation to the source code. For now, I have already made commits that copy the documentation to the IC2.cpp source file, with only minor changes to grammar and adjustments to existing comment line widths. I've also added notes to undocumented methods that refer to methods with similar functionality. See pull request below. **I invite review for this PR**, as the last thing I want to do is introduce incorrectness to the documentation. 😉 

I can see a few ways to move forward:
  1. Delete the _detailed_ method documentation in the README, and instead provide a summary of what each method does
  2. Delete the method documentation in the README and only update the source file, but within the README, refer the reader to the method definitions in the source file

I believe the first option is the best as it helps users get started without overwhelming them.

**Comment by rambo** [comment]
fixed in https://github.com/rambo/I2C/pull/16
