### ISSUE TITLE
How to write without specifying a register

### ISSUE THREAD

**Issue by VladimirAkopyan** [rambo/I2C#3]
I am using an I2C device that does not have any registers. How can I use this library to write a byte to wire without having to specify a register, just like a Wire.write() does

**Comment by rambo** [comment]
Use the low-level functions:

    I2c.start();
    I2c.sendAddress(slave_addr);
    I2c.sendByte(my_byte);
    I2c.stop();

**Comment by VladimirAkopyan** [comment]
Thanks!

**Comment by AlexisTM** [comment]
The address is in 7 bits, but the rest is the legacy 8 bits byte.

**Comment by VladimirAkopyan** [comment]
I think you should make this change public. There are quite a few I2C sensors that you have to use without a register address, such as BH1750FVI, which is really common and is really good. 
You could also Take a look at I2C api in mbed, it lets you write in any number of bytes by just asking to write an array, out of which the first byte is the address. That being said, the API you have is

**Comment by rambo** [comment]
@AlexisTM to be technically correct the address we send is 8bits, the LSB is 0 or 1 depending on whether this is a read or write transaction leaving 7 bits for the actual device address.

@VladimirAkopyan I'm not quite sure what "change" are you talking about. Those low-level functions used to be documented on Waynes website but I can't find them anymore there so maybe adding them to the README would be a good idea.

**Comment by VladimirAkopyan** [comment]
@rambo I think you should also make them public

**Comment by rambo** [comment]
@VladimirAkopyan I still don't understand what you mean by "make them public" the methods are in the public section of the class https://github.com/rambo/I2C/blob/master/I2C.h#L116

Maybe send me a pull-request of the changes you propose ?
