### ISSUE TITLE
Atmel’s SAMD21

### ISSUE THREAD

**Issue by VladimirAkopyan** [rambo/I2C#7]
I use this library with my Arduinos to get around 'arduino gets stuck if the I2C device has error / gets disconnected' issue. 
I see this is written in assembler and wouldn't work for Atmel’s SAMD21. Is there anything you can reccomend for that?

**Comment by rambo** [comment]
Assembler ? No, that's plain C but it does use direct register addressing, SAMD21 probably has different names for those registers, or completely different access-scheme for the hardware.

http://community.atmel.com/forum/i2c-help-samd21 and http://asf.atmel.com/docs/3.21.0/samd21/html/group__asfdoc__sam0__sercom__i2c__group.html might be helpful.
